theme: jekyll-theme-minimal
title: Mohamed Khodeir
logo: /assets/mk.png
description: '<p style="text-align: center"><a href="mailto:m.khodeir@mail.utoronto.ca">Email</a> / <a href="/assets/resume.pdf">Resume</a> / <a href="https://www.linkedin.com/in/khodeir/">LinkedIn</a></p>'
github:
  is_user_page: false
  is_project_page: false
