theme: jekyll-theme-minimal
title: Mohamed Khodeir
logo: /assets/mk.png
description: <br /><p><a href="/assets/resume.pdf">Resume</a> / <a href="https://www.linkedin.com/in/khodeir/">LinkedIn</a></p>
